name: chia_crypto_utils
description: Chia Crypto Utils repository provides an object model for working with Chia primitives serving as a basis for a Chia client.
version: 1.0.16
repository: https://github.com/irulast/chia-crypto-utils

environment:
  sdk: '>=2.18.0 <3.0.0'

scripts:
  integration_tests: 'dart test integration_test/ --concurrency=1'

dependencies:
  args: ^2.3.1
  bech32: ^0.2.1
  bech32m: 
    git: git@github.com:irulast/bech32m.git
  bip39: ^1.0.6
  bitcoin_base:
    git:
      ref: version_modifications
      url: git@github.com:irulast/bitcoin_base.git
  bs58: ^1.0.2
  bs58check: ^1.0.2
  collection: ^1.16.0
  compute: ^1.0.2
  crypto: ^3.0.1
  csv: ^5.0.1
  deep_pick: ^0.10.0
  equatable: ^2.0.5
  get_it: ^7.2.0
  hex: ^0.2.0
  http: ^0.13.4
  injector: ^2.0.0
  intl: ^0.17.0
  meta: ^1.7.0
  path: ^1.8.1
  quiver: ^3.0.1+1
  synchronized: ^3.0.1
  tuple: ^2.0.2
  uuid: ^3.0.6
  walletconnect_flutter_v2:
    git:
      url: git@github.com:irulast/WalletConnectDartV2.git
  yaml: ^3.1.1

dev_dependencies:
  lints: ^1.0.0
  rps: ^0.6.3
  test: ^1.19.3
  very_good_analysis: ^3.1.0

false_secrets:
  - /lib/src/networks/chia/mainnet/ssl/private_full_node.key
  - /lib/src/networks/chia/mainnet/ssl/public_full_node.key
  - /lib/src/networks/chia/testnet0/ssl/private_full_node.key
  - /lib/src/networks/chia/testnet0/ssl/public_full_node.key
  - /lib/src/networks/chia/testnet10/ssl/private_full_node.key
  - /lib/src/networks/chia/testnet10/ssl/public_full_node.key