name: Analysis and Code Coverage

on:
  push:
    branches: [ main, fix_github_actions ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the repository
      uses: actions/checkout@v1

    - name: Install Tools
      run: sudo apt update && sudo apt install lcov

    - name: Clone the Flutter repository
      uses: actions/checkout@v1
      with:
        repository: flutter/flutter
        ref: 3.3.0
        path: flutter

    - name: Add the flutter tool to the path
      run: |
        ls -al "$GITHUB_WORKSPACE/../flutter/bin"
        echo "$GITHUB_WORKSPACE/../flutter/bin" >> $GITHUB_PATH
        echo "$GITHUB_WORKSPACE/../flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
    - name: Populate the Flutter tool's cache of binary artifacts
      run: |
        flutter config --no-analytics
        flutter precache

    - name: Reconfigure git to use HTTP authentication
      run: >
        git config --global url."https://github.com/".insteadOf 'git@github.com:'

    - name: Get Flutter packages
      run: flutter pub get
    
    - name: Start simulator 
      run: | 
        cd lib/src/api/full_node/simulator/run
        docker build -f Dockerfile.enhanced . -t chia-simulator-enhanced
        docker run -p 5000:80 chia-simulator-enhanced

    - name: Run tests
      run: dart test integration_test/api_test/full_node_interface_test.dart --plain-name "should get standard coins by puzzlehashes" 

    # - name: Run tests
    #   run: flutter test ./integration_test test --coverage --concurrency=1

    # - name: Generate coverate report 
    #   run: genhtml coverage/lcov.info -o coverage

    # - name: Upload code coverage to GitHub
    #   uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074
    #   with:
    #     name: code-coverage
    #     path: coverage
