name: Analysis and Code Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FULL_NODE_SIMULATOR_URL: "https://127.0.0.1:8555"
  FULL_NODE_SIMULATOR_CERT_PATH: "/tmp/private_full_node.crt"
  FULL_NODE_SIMULATOR_KEY_PATH: "/tmp/private_full_node.key"

jobs:
  build:
    runs-on: [self-hosted, chia-dev]

    steps:
    - name: Clone the repository
      uses: actions/checkout@v1
    
    - name: Install Tools
      run: sudo apt update && sudo apt install lcov -y

    - name: Clone the Flutter repository
      uses: actions/checkout@v1
      with:
        repository: flutter/flutter
        ref: 2.8.1
        path: flutter

    - name: Add the flutter tool to the path
      run: |
        ls -al "$GITHUB_WORKSPACE/../flutter/bin"
        echo "$GITHUB_WORKSPACE/../flutter/bin" >> $GITHUB_PATH
        echo "$GITHUB_WORKSPACE/../flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH

    - name: Populate the Flutter tool's cache of binary artifacts
      run: |
        flutter config --no-analytics
        flutter precache

    - name: Get Flutter packages
      run: flutter pub get

    - name: Check that Simulator is started
      run: |
        # Waiting for simulator to work
        echo "Waiting for simulator to startup..."

        declare -i loops=0
        until $(sudo curl --output /dev/null --silent --fail --insecure --cert /root/.chia/mainnet/config/ssl/full_node/private_full_node.crt --key /root/.chia/mainnet/config/ssl/full_node/private_full_node.key -d '{}' -H "Content-Type: application/json" -X POST https://127.0.0.1:8555/get_blockchain_state); do
          printf '.'
          declare -i loops=$loops+1
          if [ $loops -gt 60 ]
          then
            echo "Simulator did not start in time"
            exit 1
          fi
          sleep 1
        done

        sudo cp /root/.chia/mainnet/config/ssl/full_node/private_full_node.crt $FULL_NODE_SIMULATOR_CERT_PATH
        sudo cp /root/.chia/mainnet/config/ssl/full_node/private_full_node.key $FULL_NODE_SIMULATOR_KEY_PATH
        sudo chown $USER $FULL_NODE_SIMULATOR_CERT_PATH
        sudo chown $USER $FULL_NODE_SIMULATOR_KEY_PATH

    - name: Run tests
      run: flutter test ./integration_test test --coverage --concurrency=1

    - name: Generate coverate report 
      run: genhtml coverage/lcov.info -o coverage

    - name: Upload code coverage to GitHub
      uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074
      with:
        name: code-coverage
        path: coverage
